### ISSUE TITLE
Enhancement : Make protocol string global 

### ISSUE THREAD

**Issue by elielnfinic** [topology-foundation/ts-drp#244]
Currently, the protocol string `"/topology/message/0.0.1"` is hardcoded in multiple places within the codebase. To improve maintainability and avoid duplication, we should extract this protocol string into a global constant.

Proposed Solution

1. Define a global constant for the protocol string in a common configuration file.
2. Replace all occurrences of the hardcoded protocol string with the global constant.

**Comment by d-roak** [comment]
agree. The protocol string is only related with libp2p, so it should be global within the `packages/network` only

**Comment by zkjamesfish** [comment]
Can I work on this?

**Comment by d-roak** [comment]
it's already being refactored on #261
